DROP DATABASE IF EXISTS POR_DB;

CREATE DATABASE POR_DB;

USE POR_DB;

CREATE TABLE USERS (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	FN VARCHAR(50) NOT NULL,
	LN VARCHAR(50),
	EMAIL VARCHAR(255) UNIQUE NOT NULL,
	PASSWORD VARCHAR(255) NOT NULL,
	ROLE VARCHAR(50) NOT NULL,
	CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE EXPENSES (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	USER_ID INT,
	TYPE VARCHAR(50),
	BILLABLE VARCHAR(5),
	PORCC VARCHAR(50),
	AMOUNT DECIMAL(10, 2),
	COMMENT TEXT,
	CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);

CREATE TABLE ITEMEXPENSES (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	USER_ID INT,
	ITEM VARCHAR(255),
	DATE DATE,
	SUBTOTAL DECIMAL(10, 2),
	CITYTAX DECIMAL(10, 2),
	TAXPERCENT DECIMAL(5, 2),
	TOTAL DECIMAL(10, 2),
	SOURCE VARCHAR(255),
	SHIPPEDFROM VARCHAR(255),
	SHIPPEDTO VARCHAR(255),
	BILLABLE VARCHAR(5),
	CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);

CREATE TABLE FOODEXPENSES (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	USER_ID INT,
	DATE DATE,
	AMOUNT DECIMAL(10, 2),
	LOCATION VARCHAR(250),
	PERSONS INT,
	TITLE VARCHAR(50),
	PURPOSE VARCHAR(255),
	BILLABLE VARCHAR(5),
	PORCC VARCHAR(50),
	CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);

CREATE TABLE MILEAGEEXPENSES (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	USER_ID INT,
	DATE DATE,
	PURPOSE VARCHAR(255),
	MILES DECIMAL(10, 2),
	BILLABLE VARCHAR(5),
	AMOUNT DECIMAL(10, 2),
	CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);

CREATE TABLE FILES (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	USER_ID INT,
	NAME VARCHAR(255),
	PATH VARCHAR(255),
	CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);